# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/findmycells',
                'doc_host': 'https://Defense-Circuits-Lab.github.io',
                'git_url': 'https://github.com/Defense-Circuits-Lab/findmycells',
                'lib_path': 'findmycells'},
  'syms': {'findmycells.core': {'findmycells.core.foo': ('core.html#foo', 'findmycells/core.py')}}}